dist: trusty
group: edge
language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.lezhin.com
cache:
  directories:
    - $HOME/.gradle
script: ./build.sh
